apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-pipeline-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-pipeline-demo
  template:
    metadata:
      labels:
        app: devops-pipeline-demo
    spec:
      containers:
        - name: devops-pipeline-demo
          image: vimala92/devops-pipeline-demo:v1
          ports:
            - containerPort: 8080